version: "3.1"

services:
  api:
    container_name: artmux-api
    restart: unless-stopped
    hostname: artmux-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
    - .:/usr/src/app
    networks:
      - artmux-network

  database:
    container_name: artmux-database
    image: postgres:14-alpine
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    volumes:
      - ./database/dev:/var/lib/postgresql/data
      # - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
    networks:
      - artmux-network

  pgadmin:
    container_name: artmux-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@artmux.dev
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - artmux-network

networks:
  artmux-network:
    driver: bridge