version: "3.1"

services:
  api:
    container_name: artmux-api
    restart: unless-stopped
    hostname: artmux-api
    image: artmux-api-dev:latest
    command: sh -c "npm run dev"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
    - .:/usr/src/app
    networks:
      - artmux-network

networks:
  artmux-network:
    external: true