version: "3.1"

services:
  api:
    container_name: artmux-api
    restart: unless-stopped
    image: artmux-api-prod:latest
    hostname: artmux-api-prod
    command: sh -c "npm run start"
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - ${PORT}:${PORT}
    networks:
      - artmux-network

networks:
  artmux-network:
    external: true